# Site settings
title: Poetry Journal
description: > # this means to ignore newlines until "baseurl:"
  Moments captured in Haiku
baseurl: "/blog" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
permalink: pretty
